[package]
name = "solfunmeme-core"
version = "0.1.0"
edition = "2021"

[dependencies]
solfunmeme-loader = { path = "../solfunmeme-loader" }
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
